# Generated by Django 5.2 on 2025-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('qoute', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
