# Generated by Django 5.2 on 2025-04-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='qoute',
            new_name='quote',
        ),
    ]
