# Generated by Django 5.2 on 2025-04-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_qoute_data_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='author',
        ),
    ]
