# Generated by Django 5.2 on 2025-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_data_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
